### ISSUE TITLE
字数统计有问题，请问一下解决方案

### ISSUE THREAD

**Issue by 2017noobman** [jackying/H-ui.admin#3]
会报如下错误
Uncaught ReferenceError: textarealength is not defined
    at HTMLTextAreaElement.onkeyup (article-add.html:83)

**Comment by jackying** [comment]
新的插件接口：http://www.h-ui.net/lib/jQuery.Huitextarealength.js.shtml

**Comment by 2017noobman** [comment]
经过测试，可以解决，感谢
